version: "3.0"

services:
  debug:
    image: webdevops/php-dev:8.1
    stdin_open: true
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_IDE_KEY=VSCODE

  # コマンド実行用コンテナ
  composer:
    image: composer:latest
    volumes:
      - ./:/app
    command: composer install
    profiles:
      - task

  test:
    image: php:8.1-cli-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php -d memory_limit=-1 ./vendor/bin/phpunit
    profiles:
      - task

  code-format:
    image: php:8.1-cli-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php -d memory_limit=-1 ./vendor/bin/php-cs-fixer fix
    profiles:
      - task

  gen-code-document:
    image: phpdoc/phpdoc:latest
    volumes:
      - ./:/data
    profiles:
      - task

  gen-code-coverage:
    image: php:8.1-cli-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - XDEBUG_MODE=coverage
    command: php -d memory_limit=-1 ./vendor/bin/phpunit -c phpunit.coverage.xml
    profiles:
      - task

  inspect-code:
    image: php:8.1-cli-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php -d memory_limit=-1 ./vendor/bin/phpstan analyse
    profiles:
      - task

  inspect-code-style:
    image: php:8.1-cli-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php -d memory_limit=-1 ./vendor/bin/php-cs-fixer fix --dry-run --diff
    profiles:
      - task

  inspect-namespace:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: composer dump-autoload --optimize --strict-psr
    profiles:
      - task
